/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsolePedidosRouteImport } from './routes/console/pedidos'
import { Route as ConsoleFinancaRouteImport } from './routes/console/financa'
import { Route as ConsoleDashboardRouteImport } from './routes/console/dashboard'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolePedidosRoute = ConsolePedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleFinancaRoute = ConsoleFinancaRouteImport.update({
  id: '/financa',
  path: '/financa',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/menu': typeof MenuRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/financa': typeof ConsoleFinancaRoute
  '/console/pedidos': typeof ConsolePedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/menu': typeof MenuRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/financa': typeof ConsoleFinancaRoute
  '/console/pedidos': typeof ConsolePedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/menu': typeof MenuRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/financa': typeof ConsoleFinancaRoute
  '/console/pedidos': typeof ConsolePedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/menu'
    | '/console/dashboard'
    | '/console/financa'
    | '/console/pedidos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/menu'
    | '/console/dashboard'
    | '/console/financa'
    | '/console/pedidos'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/menu'
    | '/console/dashboard'
    | '/console/financa'
    | '/console/pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  MenuRoute: typeof MenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/pedidos': {
      id: '/console/pedidos'
      path: '/pedidos'
      fullPath: '/console/pedidos'
      preLoaderRoute: typeof ConsolePedidosRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/financa': {
      id: '/console/financa'
      path: '/financa'
      fullPath: '/console/financa'
      preLoaderRoute: typeof ConsoleFinancaRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/dashboard': {
      id: '/console/dashboard'
      path: '/dashboard'
      fullPath: '/console/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleFinancaRoute: typeof ConsoleFinancaRoute
  ConsolePedidosRoute: typeof ConsolePedidosRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleFinancaRoute: ConsoleFinancaRoute,
  ConsolePedidosRoute: ConsolePedidosRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  MenuRoute: MenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
